Compression and cleaning moving into another PKGBUILD file

diff --git a/mkpkg b/mkpkg
--- a/mkpkg
+++ b/mkpkg
@@ -91,7 +91,7 @@ alias rmdir="command rmdir -v"
 #   CXXFLAGS     the common flags for C++ compiler
 source $mkPrefix/etc/mk.config
 
-if [[ ! "$mkPrefix" = "$PREFIX" ]]; then
+if [[ ! $(realpath "$mkPrefix") = $(realpath "$PREFIX") ]]; then
   echo "Internal error: $mkPrefix does not point to a proper installation."
   exit 1
 fi
@@ -531,9 +531,9 @@ compress_doc() {
   done
 }
 
-# strip_
-# Strip a binary or a library, removing the unneeded and debug symbols.
-strip_() {
+# get_filetype <file>
+# Return a string describing the current filetype
+get_filetype() {
   local file=$1
   local filetype=none
 
@@ -543,24 +543,38 @@ strip_() {
     filetype=library
   fi
 
-  # we need to manage the case when strip command strips itself.
-  if [[ $filetype = "executable" && "$(basename "$file")" = "strip" ]]; then
-    cp "$file" "$file.new"
-    command strip -v --strip-unneeded "$file.new"
-    rm "$file"
-    mv "$file.new" "$file"
-  else
-    case $filetype in
-      executable) log "Stripping '$(readlink -f $file)'"
-                  command strip -v --strip-unneeded "$file"
-                  ;;
-      library)    log "Stripping '$(readlink -f $file)'"
-                  command strip -v --strip-debug "$file"
-                  ;;
-      none)       ;;
-      *) error "Internal error"; exit 1
-    esac
-  fi
+  echo "$filetype"
+}
+
+# strip_
+# Strip a binary or a library, removing the unneeded and debug symbols.
+strip_() {
+  local file=
+  for file in $@; do
+    local filetype=$(get_filetype $file)
+
+    # we need to manage the case when strip command strips itself.
+    if [[ $filetype = "executable" && "$(basename "$file")" = "strip" ]]; then
+      cp "$file" "$file.new"
+      chmod 0755 "$file.new"
+      command strip -v --strip-unneeded "$file.new"
+      rm "$file"
+      mv "$file.new" "$file"
+    else
+      case $filetype in
+        executable) log "Stripping '$(readlink -f $file)'"
+                    chmod 0755 "$file"
+                    command strip -v --strip-unneeded "$file"
+                    ;;
+        library)    log "Stripping '$(readlink -f $file)'"
+                    chmod 0755 "$file"
+                    command strip -v --strip-debug "$file"
+                    ;;
+        none)       ;;
+        *) error "Internal error"; exit 1
+      esac
+    fi
+  done
 }
 
 # strip <file>
@@ -577,12 +591,34 @@ strip() {
   done
 }
 
-# reset_rpath <file>
-# Reset the RPATH of the file
-reset_rpath() {
+# reset_rpath_ <file>
+# Reset the RPATH of the file.
+reset_rpath_() {
+  local file=
   for file in $@; do
-    log "Reset the RAPTH of '$file'"
-    "$mkPrefix"/bin/patchelf --set-rpath "" $file
+    local filetype=$(get_filetype $file)
+    case $filetype in
+      executable | library )
+        log "Reset the RAPTH of '$file'"
+        "$mkPrefix"/bin/patchelf --set-rpath "" $file
+        ;;
+      none) ;;
+      *) error "Internal error"; exit 1
+    esac
+  done
+}
+
+# reset_rpath <file>
+# Reset the RPATH of the file. If the argument is a directory, then all the
+# contained files are resetted recursively.
+reset_rpath() {
+  local file=
+  for file in $@; do
+    if [[ -d $file ]]; then
+      find $file -type f -print0 | while IFS= read -r -d '' file; do reset_rpath_ $file; done
+    else
+      reset_rpath_ $file
+    fi
   done
 }
 
@@ -670,6 +706,7 @@ run() {
   build $@
   message "Installing in '$dstdir'"
   package $@
+  update_linker_cache
 }
 
 # execute the build script
